const express = require("express");
const router = express.Router();
const controller = require("./controller");
//router.post("/", controller.provideSim);
router.get("/", controller.getAll);
router.get("/getBySSN", controller.getByESN);
router.patch("/", controller.updateOrderInfo);
router.get("/getByMDN", controller.getByMDN);
router.get("/history", controller.userServicesHistory);
router.post("/", controller.order);
router.put("/", controller.updateOrder);
router.delete("/deleteOrder", controller.deleteOrder);
router.get("/getOrderById", controller.getOrderById);
router.get("/getOrderByenrollmentId", controller.getOrderByenrollmentId);
router.post("/holdOrder", controller.holdOrder);
router.post("/restoreHoldOrder", controller.restoreHoldOrder);
router.post("/createLable", controller.createLable);
router.post("/assignUser", controller.assignUser);
router.post("/unassignUser", controller.unassignUser);
router.get("/listAccountTags", controller.listAccountTags);
router.post("/addTag", controller.addTag);
router.get("/listOrderByTag", controller.listOrderByTag);
router.get("/listOrders", controller.listOrders);
router.post("/markShipped", controller.markShipped);
router.post("/removeTag", controller.removeTag);
router.get("/getTrackingNumber", controller.getTrackingNumber);
module.exports = router;
