const Joi = require("joi");
module.exports = {
  createValidation: Joi.object({
    createdBy: Joi.string().required(),
    serviceProvider: Joi.string().required(),
    name: Joi.string().required(),
    description: Joi.string(),
    type: Joi.string().required(),
    dataAllowance: Joi.number().required(),
    dataAllowanceUnit: Joi.string().required(),
    voiceAllowance: Joi.number().required(),
    voiceAllowanceUnit: Joi.string(),
    textAllowance: Joi.number().required(),
    textAllowanceUnit: Joi.string().required(),
    duration: Joi.number().required(),
    durationUnit: Joi.string().required(),
    price: Joi.number().required(),
    additionalFeatures: Joi.array(),
    termsAndConditions: Joi.string(),
    restrictions: Joi.array(),
    planId: Joi.string().required(),
    inventoryType: Joi.string().required(),
  }),
  updateValidation: Joi.object({
    updatedBy: Joi.string().required(),
    serviceProvider: Joi.string().required(),
    planId: Joi.string().required(),
    name: Joi.string().optional(),
    description: Joi.string().optional(),
    type: Joi.string().optional(),
    dataAllowance: Joi.number().optional(),
    dataAllowanceUnit: Joi.string().optional(),
    voiceAllowance: Joi.number().optional(),
    voiceAllowanceUnit: Joi.string().optional(),
    textAllowance: Joi.number().optional(),
    textAllowanceUnit: Joi.string().optional(),
    duration: Joi.number().optional(),
    durationUnit: Joi.string().optional(),
    price: Joi.number().optional(),
    additionalFeatures: Joi.array().optional(),
    termsAndConditions: Joi.string().optional(),
    restrictions: Joi.array().optional(),
    inventoryType: Joi.string().required(),
  }),
};
